// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzRcgG7eLo1vAaDJPPJpvVzvzRK0CWFaI',
    appId: '1:1027424403546:web:0670b8398e480adc28d863',
    messagingSenderId: '1027424403546',
    projectId: 'unibazzar-e331c',
    authDomain: 'unibazzar-e331c.firebaseapp.com',
    storageBucket: 'unibazzar-e331c.firebasestorage.app',
    measurementId: 'G-34CG2FKZ84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa4BWSXZSY9jAu2ie0P6sUCG3sS2GvP4s',
    appId: '1:1027424403546:android:f0c996bc9816d1a228d863',
    messagingSenderId: '1027424403546',
    projectId: 'unibazzar-e331c',
    storageBucket: 'unibazzar-e331c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuJrNHroZv6QVbS4B2A5baNJr_jcyxLzc',
    appId: '1:1027424403546:ios:d855c12b0571eb8928d863',
    messagingSenderId: '1027424403546',
    projectId: 'unibazzar-e331c',
    storageBucket: 'unibazzar-e331c.firebasestorage.app',
    iosBundleId: 'com.example.unibazzar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuJrNHroZv6QVbS4B2A5baNJr_jcyxLzc',
    appId: '1:1027424403546:ios:d855c12b0571eb8928d863',
    messagingSenderId: '1027424403546',
    projectId: 'unibazzar-e331c',
    storageBucket: 'unibazzar-e331c.firebasestorage.app',
    iosBundleId: 'com.example.unibazzar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzRcgG7eLo1vAaDJPPJpvVzvzRK0CWFaI',
    appId: '1:1027424403546:web:c545028929eb553828d863',
    messagingSenderId: '1027424403546',
    projectId: 'unibazzar-e331c',
    authDomain: 'unibazzar-e331c.firebaseapp.com',
    storageBucket: 'unibazzar-e331c.firebasestorage.app',
    measurementId: 'G-EH8S24CD8C',
  );
}
